package com.lightframework.ioc.core;

/**
 * Phase 1: Compile-time DI contract. Implementations are generated by LightProcessor.
 */
public interface BeanInjector<T> {
    T create();
    void inject(T instance, DefaultListableBeanFactory factory) throws Exception;
    default void postConstruct(T instance) throws Exception {}
}
